AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  KMSKey:
    Type: String
    Description: "key for decrypting credstash"
Resources:
  CodebuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "codebuild-credstash"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              ## logs
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Join ["", ["arn:aws:logs:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId" ,":log-group:/aws/codebuild/*"]]
              ## Credstash
              - Effect: "Allow"
                Action:
                  - "kms:Decrypt"
                  - "kms:GenerateDataKey"
                Resource: !Join ["", ["arn:aws:kms:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId" ,":key/", !Ref "KMSKey"]]
              - Effect: "Allow"
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:Query"
                  - "dynamodb:Scan"
                  - "dynamodb:PutItem"
                Resource: !Join ["", ["arn:aws:dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId",":table/credential-store"]]
              ## add ecr repo for bdp
